Rif 28
Rock-n-Roll-Coders/RIFFIN-FRONTEND pull request #31
Opened 2023-07-06 00:12 UTC by dabyzness

Downgrade to react-router-dom v5. Add Prompts to prevent user from leaving unsaved tablature data

2023-07-08 01:30 UTC, RyanSUP requested changes
Good job with the navigation stuff dude. I wonder how many times I will use the navigate hook instead of the history hook 😂.

The prompt for unsaved changes is working great! Is there any way to customize or is it a browser thing? Maybe we can throw a MUI backdrop on the screen when the prompt happens so it is easier to focus? https://mui.com/material-ui/react-backdrop/

There appears to be a few bugs: 
* App crashes when saving as a logged out user. This has to do with my useless if statement in the TagBar useEffect.
* Saving the tablature as a logged out user errors out with a 401 code, but the frontend still displays a "Success" notification. Should it run through the `login/signup => save => return to editor` flow at this point?

I stashed all the merge conflicts but I didn't push them, we can get together to resolve them.

2023-07-08 01:30 UTC, RyanSUP commented on src/pages/RiffinEditor/components/SaveTabButton.js
> +          // history.push(`/edit/${tablatureFromResponse._id}`, { replace: true });
should this  comment be deleted?

2023-07-08 01:30 UTC, RyanSUP commented on src/AppRouter.js
> +    {/* <Route path="/" element={<PageLayout contentCenter={<Home />} />} /> */}
Can this be deleted?

2023-07-08 01:30 UTC, RyanSUP commented on src/AppRouter.js
I wonder why they chose to use the element prop in V6 instead of the wrapper? Good stuff though

2023-07-08 01:30 UTC, RyanSUP commented on src/pages/RiffinEditor/components/SaveTabButton.js
> +    console.log("EDIT", editor);
We can remove these logs if you're done with development here. I am definitely guilty of forgetting to delete these (dont look at the homepage logs lmao)

2023-07-08 01:30 UTC, RyanSUP commented on src/pages/RiffinEditor/components/SaveTabButton.js
> +  const compareEditors = (a, b) => {
I think this is good for now, and we can keep it in this file but since it is a pure function we can move it out of the component so it doesn't get rerendered.

2023-07-08 01:30 UTC, RyanSUP commented on src/pages/RiffinEditor/components/SaveTabButton.js
> +      console.log("1");
The logs can be removed if you're done with them.

2023-07-08 01:30 UTC, RyanSUP commented on src/pages/RiffinEditor/components/SaveTabButton.js
> +  }, [editor]);
This is missing the initialState dependency. I did some testing and I don't think it matters but it will stop the linter from bitching about it

2023-07-19 15:39 UTC, dabyzness commented
Writing here to address the main concerns of the app crashing:
The app will crash when trying to save as a logged in user. This is due to the disconnect between this branch, RIF-28, and another branch RIF-112. This branch was solely for preventing the user from leaving the page through the use of Prompt, which required downgrading react-router-dom. RIF-112 is responsible for creating the SignUp/Login dialog that would appear when a logged out user is attempting to save and handle all of the necessary functionality.

All of that functionality is already written within RIF-112, but there are 2 reasons I haven't requested a PR. The first being that I was working on a branch of version-0 before you moved all of the files around in the directory. The second being that it still used react-router-dom@v6.

So the goal of this PR, RIF-28, was to merge to version-0 then create a new, more updated branch of RIF-112 and copy the necessary changes over to. But now, I'm thinking I should just create a new RIF-112 by branching off of RIF-28 and then submitting a PR that way.

I was planning on keeping many of the console logs for testing on RIF-112 but I can just add them back in afterwards if necessary. Sorry this is convoluted af. I'll fix it.

2023-07-19 15:41 UTC, dabyzness commented on src/AppRouter.js
> +    {/* <Route path="/" element={<PageLayout contentCenter={<Home />} />} /> */}
deleted

2023-07-19 15:42 UTC, dabyzness commented on src/pages/RiffinEditor/components/SaveTabButton.js
> +    console.log("EDIT", editor);
removed

2023-07-19 15:48 UTC, dabyzness commented on src/pages/RiffinEditor/components/SaveTabButton.js
> +  const compareEditors = (a, b) => {
done

2023-07-19 15:50 UTC, dabyzness commented on src/pages/RiffinEditor/components/SaveTabButton.js
> +  }, [editor]);
done

2023-07-19 15:50 UTC, dabyzness commented on src/pages/RiffinEditor/components/SaveTabButton.js
> +          // history.push(`/edit/${tablatureFromResponse._id}`, { replace: true });
done

2023-07-23 16:27 UTC, RyanSUP approved these changes

2023-07-23 16:27 UTC, merged